import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Bank App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='main'>
        <div className='wrapper'>
          <header className='header'>
            <div className='header__wrap'>
              <a href='/' className='logo'>
                <span></span>
              </a>

              <div className='pagination'>
                <span className='active'></span>
              </div>
            </div>
            <div className='slider'>
              <div className='slide'>
                <h1>
                  <span>We are in business to</span>
                  <span>help you do business.</span>
                </h1>
              </div>
            </div>
          </header>

          <section className='login'>
            <h2>Good morning</h2>
            <p>Sign on to manage your accounts.</p>

            <div className='inputs'>
              <input type='text' placeholder='Username' />
              <input type='text' placeholder='Password' />
              <button>Sign in</button>
            </div>

            <div className='options'>
              <a href=''>Forgot username</a>
              <span>|</span>
              <a href=''>password</a>
            </div>
          </section>
        </div>
      </main>
    </>
  );
}
